### ISSUE TITLE
How can I use boxxy to install boxxy?

### ISSUE THREAD

**Issue by blurayne** [queer/boxxy#11]
`install.sh` is misbehaving and wants to put it's binary to `~/bin` AND NOT `~/.local/bin` which is XDG standard?

I want to use boxxy to `install.sh` to `~/.local/bin` ?

Or might it be possible to customize the path in `install.sh`?

Anyway, cool idea. But too much work to write a config for every "misbehaving" application. A generic wrapper (scanning what bins are in your PATH) and a repository with predefined configs would be cool.

**Comment by queer** [comment]
`install.sh` is a tool for me; I didn't expect people to actually use it :sweat_smile: 

> A generic wrapper (scanning what bins are in your PATH) and a repository with predefined configs would be cool.

I would love to do this someday; I just don't have enough data yet.

**Comment by blurayne** [comment]
...until a developer setup comes along with hardcoded `~/.aws/credentials` etc.

Maybe putting it to a LD_PRELOAD lib may be a better effort? Or even a kernel module? Basically it could redirect everything dot-something I the home directory to ./config except it is .cache or .local ... 

Well, just an experimental idea. I guess people don't care much about cluttering their homedir with dot files and we'll have to surrender 😑
