### ISSUE TITLE
Generate separate rules repo based on Arch's XDG_* list

### ISSUE THREAD

**Issue by queer** [queer/boxxy#13]
https://wiki.archlinux.org/title/XDG_Base_Directory

**Comment by IncredibleLaser** [comment]
Just for correctness, while these variables are listed in the Arch Wiki, this is the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), as the Wiki states in the first sentence. It's not Arch specific or anything.

**Comment by queer** [comment]
Added in [379d5c4](https://github.com/queer/boxxy/commit/379d5c437d25d6081b64553c346092f1526a2948).
