### ISSUE TITLE
A fully specified binary path doesn't get matched correctly

### ISSUE THREAD

**Issue by Afluttera** [queer/boxxy#22]
If you were to have multiple binaries of the same name in your path (say, if you wanted to provide wrappers around binaries in `/usr/bin` in `~/.local/bin`), then you may want to be able to specify a rule more exactly than just by the name of the binary.

If you had a config like this:
```yaml
rules:
  - name: "test rule"
    target: "~/test"
    rewrite: "~/othertest"
    mode: "directory"
    only:
      - "/usr/bin/test"
```
calling boxxy like this: `boxxy /usr/bin/test` would fail to match the rule. It *would* match when called as just `boxxy test` though, which feels a bit unintuitive.

It seems to be because it's comparing the invoking name to *just* the file name of the rule in `applies_to_binary()`.

More helpful behavior might be to apply the rule generically to any binary path if written plainly (with the `only` being the same as the file name, like `test`), or apply it specifically if it's a full path name (like `/usr/bin/test`)? Just comparing against the filename of the invoking command as well would be an improvement, though.

I appreciate your work on the project. It's nice to be able to tidy up my home directory a bit more.

**Comment by queer** [comment]
Thanks for the report! This is fixed in `0.3.6` which will be fully released in a few minutes: https://github.com/queer/boxxy/releases/tag/v0.3.6

**Comment by Afluttera** [comment]
It seems as though this still causes some issues with symlinks, unfortunately? I'm trying to work with VSCode OSS, which I use as `code`, which is provided by the binary `/usr/bin/code`, which itself is a *symlink* to `/usr/bin/code-oss`. So if I had this as my `only`:
```
only:
  - "code"
  - "/usr/bin/code"
  - "code-oss"
  - "/usr/bin/code-oss"
```
and called boxxy like this: `boxxy /usr/bin/code`, none of them would match, when I would at the very least expect that at least the second one would. Specifically, the line of comparisons currently seems to end up like this:
```
"/usr/bin/code" == "code"
"/usr/bin/code" == "code"

"/usr/bin/code" == "code-oss"
"/usr/bin/code" == "/usr/bin/code-oss"

"/usr/bin/code" == "code-oss"
"/usr/bin/code" == "code-oss"

"/usr/bin/code" == "code-oss"
"/usr/bin/code" == "/usr/bin/code-oss"
 ```
It might be nice if the info about what program was boxed (`INFO  boxxy::enclosure > boxed "{program name" ♥"`) would output something that's guaranteed to match if used as an `only` rule, to help alleviate this sort of problem as well. It's a bit perplexing to copy the text verbatim and have it still not match. Maybe there could always be an additional check against the literal strings the user put in, as a safeguard against unmatchable program names?

Thanks again for your work, and sorry for the weird edge cases.

**Comment by queer** [comment]
> It seems as though this still causes some issues with symlinks, unfortunately?

Will have to test, thanks for letting me know!

> It might be nice if the info about what program was boxed

You can see this in debug output `env RUST_LOG=debug ...`.

**Comment by queer** [comment]
Sorry for the delay :pensive: Not been well lately

I think 7cdfe65 (and everything after it) will do the right thing, or at least have more-useful debug logging; if you can pull and build it yourself that'd be great, but if you can't then I can cut a small release or something.

**Comment by Afluttera** [comment]
Unfortunately, it seems to error out due to unpacking the rule canonicalization when called with `boxxy /usr/bin/code`, in this case because the "code" rule is before "/usr/bin/code".
```
DEBUG boxxy::enclosure > processing path creation for rule 'redirect vscode from ~/.vscode-oss to ~/.local/share/vscode'
DEBUG boxxy::enclosure::rule > redirect vscode from ~/.vscode-oss to ~/.local/share/vscode: testing program: program="/bin/usr/code", rule_binary="code"
DEBUG boxxy::enclosure::rule > redirect vscode from ~/.vscode-oss to ~/.local/share/vscode: comparing file names: program="/bin/usr/code", rule binary file_name="code"
DEBUG boxxy::enclosure::rule > redirect vscode from ~/.vscode-oss to ~/.local/share/vscode: comparing binaries by given paths: program="/bin/usr/code", rule_binary="code"
Error: 
   0: No such file or directory (os error 2)

Location:
   src/enclosure/rule.rs:104

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 5 frames hidden ⋮                               
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual::hf825e389f41fa3bd
      at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:2107
   7: boxxy::enclosure::rule::Rule::test_program::h55e437e89ed80b1f
      at ~/boxxy/src/enclosure/rule.rs:104
       102 │ 
       103 │         // Fully expand rule path and program path, and compare. ex. /usr/bin/ls == /bin/ls
       104 >         let expanded_rule_binary = rule_binary.canonicalize()?;
       105 │         let expanded_user_program = fs.fully_expand_path(&program.to_string_lossy().to_string())?;
       106 │         debug!("{}: comparing binaries by full expansion: expanded_user_program={expanded_user_program:?}, expanded_rule_binary={expanded_rule_binary:?}", self.name);                          
```
Wrapping the two checks that use it in a
```
if let Ok(expanded_rule_binary) = rule_binary.canonicalize() {
```
fixed the issue, though, and also seems correct.

Oh, and it's maybe unrelated to this particular issue, but you have an typo in your debug logging for the `which` resolving:
https://github.com/queer/boxxy/commit/7cdfe6502038d3275ad85f11149dffd95b0d4ecd#diff-eca5272b4a2e4f02eebc587fecdd6c1c73692ed177a7e4e4d02b4fcbb6fc18b8R122
which really threw me for a loop when I was trying to work out why things were suddenly failing. Turns out I typo'd the argument as `boxxy /bin/usr/code`, but getting a `0: cannot find binary path` in rule resolving is a sort of unexpected failure mode of providing an invalid executable file. I can create a new issue for that after, though.

And no worries. Things happen, and you don't owe random people pestering you with issues a prompt response. I hope things get better.

**Comment by queer** [comment]
> Turns out I typo'd the argument as `boxxy /bin/usr/code`, but getting a `0: cannot find binary path` in rule resolving is a sort of unexpected failure mode of providing an invalid executable file. I can create a new issue for that after, though.

That would be much appreciated!

> Oh, and it's maybe unrelated to this particular issue, but you have an typo in your debug logging for the `which` resolving

This is what I get for writing code while unwell lmao, thanks for pointing it out!

---

I don't use `code-oss` personally, so I've been struggling w/ finding a better way to recreate this. Thanks for the patience w/ testing! I believe 345171e fixes this. Given this config:

```yaml
rules:
- name: "rewrite ~/.aws -> ~/.config/aws"
  target: "~/.aws"
  rewrite: "~/.config/aws"
  only:
    - "/bin/ls"
    - "python3.10"
```

and this in `/usr/bin`:

```sh
▶  ls -lah /usr/bin/python
lrwxrwxrwx 1 root root 7 Mar  5 17:26 /usr/bin/python -> python3*
▶  ls -lah /usr/bin/python3
lrwxrwxrwx 1 root root 10 Mar  5 17:26 /usr/bin/python3 -> python3.10*
▶  ls -lah /usr/bin/python3.10
-rwxr-xr-x 1 root root 14K Mar  5 17:26 /usr/bin/python3.10*
▶  
```

it seems to work correctly finally!

<details>
<summary>Successful `boxxy` run!</summary>
<pre><code>
git:(mistress) 2 | ▶  env RUST_LOG=debug cargo run -- /usr/bin/python -c "import os;r=os.listdir('/home/amy/.aws');print('test:', r)"
Compiling boxxy v0.3.6 (/misc/ssd1/Projects/amyware/boxxy)
    Finished dev [unoptimized + debuginfo] target(s) in 2.45s
    Running `target/debug/boxxy /usr/bin/python -c 'import os;r=os.listdir('\''/home/amy/.aws'\'');print('\''test:'\'', r)'`
DEBUG boxxy > loading config: boxxy-dev.yaml
INFO  boxxy > loaded 1 rule(s)
DEBUG boxxy::enclosure > processing path creation for rule 'rewrite ~/.aws -> ~/.config/aws'
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: testing program: program="/usr/bin/python", rule_binary="/bin/ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing file names: program="/usr/bin/python", rule binary file_name="ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing binaries by given paths: program="/usr/bin/python", rule_binary="/bin/ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing binaries by full expansion: expanded_user_program="/usr/bin/python3.10", expanded_rule_binary="/usr/bin/ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing binaries as resolved symlinks: resolved_user_program="/usr/bin/python3.10", resolved_rule_binary="/usr/bin/ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing binaries with which(1): which_user_program="/usr/bin/python", which_rule_binary="/bin/ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: rule didn't match anything, does not apply!
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: testing program: program="/usr/bin/python", rule_binary="python3.10"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing file names: program="/usr/bin/python", rule binary file_name="python3.10"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing binaries by given paths: program="/usr/bin/python", rule_binary="python3.10"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing rule binary to user program as resolved symlinks: resolved_user_program="/usr/bin/python3.10", rule_binary="python3.10"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: rule binary "python3.10" matches user program file name for "/usr/bin/python3.10"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: rule applies to binary!
DEBUG boxxy::enclosure       > ensuring path: "/home/amy/.aws"
DEBUG boxxy::enclosure       > rewriting to: "/home/amy/.config/aws"
DEBUG boxxy::enclosure       > rewrote base bath "/home/amy/.config/aws" => "/home/amy/.aws"
DEBUG boxxy::enclosure       > setup root
DEBUG boxxy::enclosure::fs   > setting up root for small-toast-2715
DEBUG boxxy::enclosure       > bind mount root rw
DEBUG boxxy::enclosure::fs   > bind mount "/" onto "/tmp/boxxy-containers/small-toast-2715" as rw
DEBUG boxxy::enclosure::fs   > bind mount "/" onto "/tmp/boxxy-containers/small-toast-2715"
DEBUG boxxy::enclosure       > processing rule 'rewrite ~/.aws -> ~/.config/aws'
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: testing program: program="/usr/bin/python", rule_binary="/bin/ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing file names: program="/usr/bin/python", rule binary file_name="ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing binaries by given paths: program="/usr/bin/python", rule_binary="/bin/ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing binaries by full expansion: expanded_user_program="/usr/bin/python3.10", expanded_rule_binary="/usr/bin/ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing binaries as resolved symlinks: resolved_user_program="/usr/bin/python3.10", resolved_rule_binary="/usr/bin/ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing binaries with which(1): which_user_program="/usr/bin/python", which_rule_binary="/bin/ls"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: rule didn't match anything, does not apply!
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: testing program: program="/usr/bin/python", rule_binary="python3.10"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing file names: program="/usr/bin/python", rule binary file_name="python3.10"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing binaries by given paths: program="/usr/bin/python", rule_binary="python3.10"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: comparing rule binary to user program as resolved symlinks: resolved_user_program="/usr/bin/python3.10", rule_binary="python3.10"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: rule binary "python3.10" matches user program file name for "/usr/bin/python3.10"
DEBUG boxxy::enclosure::rule > rewrite ~/.aws -> ~/.config/aws: rule applies to binary!
INFO  boxxy::enclosure       > applying rule 'rewrite ~/.aws -> ~/.config/aws'
DEBUG boxxy::enclosure       > source exists: true
DEBUG boxxy::enclosure       > target exists: true
DEBUG boxxy::enclosure::fs   > bind mount "/home/amy/.config/aws" onto "/tmp/boxxy-containers/small-toast-2715/home/amy/.aws" as rw
DEBUG boxxy::enclosure::fs   > bind mount "/home/amy/.config/aws" onto "/tmp/boxxy-containers/small-toast-2715/home/amy/.aws"
INFO  boxxy::enclosure       > * ~/.aws -> ~/.config/aws
DEBUG boxxy::enclosure       > rewrote base bath "/home/amy/.config/aws" => "/tmp/boxxy-containers/small-toast-2715/home/amy/.aws"
DEBUG boxxy::enclosure       > chrooted to /tmp/boxxy-containers/small-toast-2715
DEBUG boxxy::enclosure       > child stopped!
DEBUG boxxy::enclosure::linux > mapped uids {
    Uid(
        1000,
    ): Uid(
        1000,
    ),
}
DEBUG boxxy::enclosure::linux > mapped gids {
    Gid(
        985,
    ): Gid(
        985,
    ),
}
DEBUG boxxy::enclosure        > finished setting up uid/gid mapping
DEBUG boxxy::enclosure       > running command: "/usr/bin/python"
INFO  boxxy::enclosure       > boxed "/usr/bin/python" ♥
test: ['credentials', 'config', 'asdf']
DEBUG boxxy::enclosure       > command exited with status: ExitStatus(unix_wait_status(0))
DEBUG boxxy::enclosure::fs    > cleaning up root for small-toast-2715
DEBUG boxxy::enclosure        > cleaning up 0 path(s) ♥
DEBUG boxxy::enclosure        > exiting with status 0
</code></pre>
</details>

**Comment by Afluttera** [comment]
Yep, that seems to fix it for me as well. Thank you for your work!

**Comment by queer** [comment]
Awesome! I'll cut a release later, thanks so much for the patience here :heart:
