### ISSUE TITLE
Question: Work with hardened kernel?

### ISSUE THREAD

**Issue by RAVENz46** [queer/boxxy#225]
Is this work with hardened kernel (`kernel.unprivileged_userns_clone=0`)?

**Comment by queer** [comment]
No. boxxy relies on unprivileged user namespaces in order to provide all the functionality it does. There is a chance it may work without unprivileged user namespaces, specifically by running it as root, but this is untested and I cannot guarantee any functionality.

**Comment by RAVENz46** [comment]
@queer I see, Thank you!
