### ISSUE TITLE
Root owned files/directories are owned by "nobody" when running under boxxy

### ISSUE THREAD

**Issue by Afluttera** [queer/boxxy#234]
```
> ls -la /etc/environment 
-rw-r--r-- 1 root root 97 Apr 11 04:47 /etc/environment
```

```
> boxxy ls -la /etc/environment 
 INFO  boxxy::config > loading rules from /home/aflutter/.config/boxxy/boxxy.yaml
 INFO  boxxy::config > loaded 0 total rule(s)
 INFO  boxxy::enclosure > boxed "ls" ♥
-rw-r--r-- 1 nobody nobody 97 Apr 11 04:47 /etc/environment
```

I'm running into this problem because ssh checks to make sure a file is owned by root, and errors out for security reasons if not (`Bad owner or permissions on /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf`).

Somehow, this is only a recent issue. I've used boxxy with ssh regularly until around June when it broke. I checked a few older version of boxxy, with the oldest being 5.1, and they all had the issue, though.

**Comment by queer** [comment]
This is related to #6.

**Comment by queer** [comment]
#6 is the tracking issue for this problem.
