### ISSUE TITLE
Q: What are the performance/power implications of using this?

### ISSUE THREAD

**Issue by mh166** [queer/boxxy#24]
Hi,

thanks for this nice project. It surely fills a need I didn't know I had. 😉  But now I find it really nice to be able to declutter my home dir.

But before I go along and throw it at every possible "intruder": do you know or have an estimate about the impact on the performance of the programs run within `boxxy`? And does it have any noticeable impact on the battery life of mobile devices?

Would be nice to know. :)

**Comment by queer** [comment]
afaik the impact is literally zero -- it should be **exactly** as much impact as `unshare -rm` unless you're using the `ptrace` features.
