### ISSUE TITLE
Target read-only files/directories

### ISSUE THREAD

**Issue by yannleretaille** [queer/boxxy#3]
Right now, targeting read-only files or directories fails (with a panic).

Supporting this case would be useful for (examples):
- re-map the location of configuration files that are not supposed to be modified by the target application
- provide modified/program-local system configuration files for a specific target application 

In any case, this should probably not fail with a panic!

**Comment by queer** [comment]
Thanks for the report! Do you happen to have a copy of the panic available?

**Comment by queer** [comment]
I _believe_ this is fixed as of 5d7421ae4b7ae4b61a8405a2b2809ac2f4b73a44 (released in 0.2.6)

**Comment by yannleretaille** [comment]
Thank you!
