### ISSUE TITLE
Handle being given an invalid program as an argument more gracefully

### ISSUE THREAD

**Issue by Afluttera** [queer/boxxy#32]
If you pass a program that doesn't exist to boxxy, you get an error in `rule.rs` about failing to find the binary path, and a bunch of output indicating it may be a problem with `boxxy` itself:
```
~> boxxy testt
 INFO  boxxy > loaded 2 rule(s)
Error: 
   0: cannot find binary path

Location:
   src/enclosure/rule.rs:136

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Consider reporting this error using this URL: https://github.com/queer/boxxy/issues/new?title=%3Cautogenerated-issue%3E&body=%23%23+Error%0A%60%60%60%0AError%3A+%0A+++0%3A+cannot+find+binary+path%0A%60%60%60%0A%0A%23%23+Metadata%0A%7Ckey%7Cvalue%7C%0A%7C--%7C--%7C%0A%7C**version**%7C0.3.6%7C%0A
```
This should probably be explicitly checked for before testing against rules at all, and present a more clear, less generic error.

**Comment by queer** [comment]
Thanks for the report! The fix for this and #22 will be out in `0.4.0` soon :D
