### ISSUE TITLE
Request: "Quiet" option

### ISSUE THREAD

**Issue by garaiza-93** [queer/boxxy#73]
I love this tool already, and I integrate it into my dev environments using Nix. However, it's a little too noisy for my liking when I'm using the tool repeatedly. Is it feasible to create a flag to reduce boxxy's output to the terminal?

**Comment by queer** [comment]
The way to do it right now would be to use the log level flag (`-l warn` or `--log-level=error` or similar, basically any level higher than `info`). I'm open to the idea of a `-q` or similar, I'm just not certain if it's needed right now.

**Comment by garaiza-93** [comment]
I understand if it's not a priority. I've tried your suggestion and I can work with this :)
Thanks again for the awesome tool!

**Comment by queer** [comment]
Feel free to re-open this if it becomes bothersome! I'm absolutely not against the idea in general (:
